kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: gulimall-coupon
  name: gulimall-coupon
  namespace: gulimall
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  replicas: 1
  selector:
    matchLabels:
      app: gulimall-coupon
  strategy:
    type: RollingUpdate  #滚动更新  停止一个 开启一个
    rollingUpdate:
      maxSurge: 100%    #更新期间 存活的最大 pod数量
      maxUnavailable: 100%  #最大不可用 更新期间 4个中之只能有一个不可用
  template:
    metadata:
      labels:
        app: gulimall-coupon
    spec:
      containers:
        - name: gulimall-coupon
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: gulimall-coupon
  name: gulimall-coupon
  namespace: gulimall
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30003
  selector:
    app: gulimall-coupon
  sessionAffinity: None
  type: NodePort