server:
  port: 20000
spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.100
    port: 6379
  session:
    store-type: redis
github:
  clientID:
  clientSecrets: 
  authorizeUrl: https://github.com/login/oauth/authorize
  callbackUrl: http://auth.gulimall.com/oauth2/callback
  accessTokenUrl: https://github.com/login/oauth/access_token
  userInfoUrl: https://api.github.com/user
