#server:
#  port: 9999
#spring:
#  application:
#    name: gulimall-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
spring:
  cloud:
    gateway:
      routes:
        - id: gulimall-product
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            #/api/product ->  /product
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id:  gulimall-third-party
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            #/api/thirdparty/ ->  /
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}
        - id: gulimall-ware
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            #/api/ware/->  /ware
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: gulimall-member
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            #/api/member/->  /member
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: gulimall-search
          uri: lb://gulimall-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        #秒杀
        - id: gulimall-coupon
          uri: lb://gulimall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        #秒杀
        - id: gulimall-seckill
          uri: lb://gulimall-seckill
          predicates:
            - Path=/api/seckill/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: renren-fast
          uri: lb://renren-fast
          predicates:
            - Path=/api/**  #没有匹配到的最后都交给你
          filters:
            #/api/** ->  /api/renren-fast
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        #gateway host路由规则 必须放在最后面 因为host断言符合所有路径映射

        #gulimall-cart
        - id: gulimall-cart-route
          uri: lb://gulimall-cart
          predicates:
            #按照host断言
            - Host=cart.gulimall.com

        #gulimall-search
        - id: gulimall-search-route
          uri: lb://gulimall-search
          predicates:
            #按照host断言
            - Host=search.gulimall.com

        - id: gulimall-auth-route
          uri: lb://gulimall-auth-server
          predicates:
            #按照host断言
            - Host=auth.gulimall.com

        - id: gulimall-order-route
          uri: lb://gulimall-order
          predicates:
            #按照host断言
            - Host=order.gulimall.com

        - id: gulimall-host-route
          uri: lb://gulimall-product
          predicates:
            #按照host断言
            - Host=gulimall.com,item.gulimall.com
