server:
  port: 30000
spring:
  application:
    name: gulimall-third-party
  zipkin:
    base-url: http://192.168.56.100:9411
    #关闭zipkin 的服务发现 不然spring cloud 会把zipkin的url 当作服务名称
    discovery-client-enabled: false
    # 设置zipkin 使用http的方式传输数据
    sender:
      type: web

  sleuth:
    sampler:
      #采样率介于0到1之间， 默认为0.1 即10%  1表示全部采集
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719   #微服务与控制台传送信息的端口 假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
        dashboard: localhost:8333  #sentinel 控制台地址
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: phoenixhell-gulimall
      sms:
        expire: 5
feign:
  sentinel:
    enabled: true