server:
  port: 10003
spring:
  application:
    name: gulimall-cart
  redis:
    host: 192.168.56.100
  thymeleaf:
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  session:
    store-type: redis
gulimall:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10
    work-queues: 100000