server:
  port: 11000
spring:
  application:
    name: gulimall-ware
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.100:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  zipkin:
    base-url: http://192.168.56.100:9411
    #关闭zipkin 的服务发现 不然spring cloud 会把zipkin的url 当作服务名称
    discovery-client-enabled: false
    # 设置zipkin 使用http的方式传输数据
    sender:
      type: web
  sleuth:
    sampler:
      #采样率介于0到1之间， 默认为0.1 即10%  1表示全部采集
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719   #微服务与控制台传送信息的端口 假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
        dashboard: localhost:8333  #sentinel 控制台地址
  rabbitmq:
    host: 192.168.56.100
    port: 5672
    virtual-host: /
    publisher-confirm-type: correlated #开启发送端确认
    publisher-returns: true            #开启消息发送抵达队列的确认
    template:
      mandatory: true                  #只要抵达队列，以异步方式优先回调我们这个
    listener:
      simple:
        acknowledge-mode: manual    #消费端手动ack 消息
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
logging:
  level:
    com.phoenixhell: debug


feign:
  sentinel:
    enabled: true